import advantage from './advantage.png';
import black from './black.png';
import blue from './blue.png';
import darkside from './darkside.png';
import despair from './despair.png';
import downgrade from './downgrade.png';
import fail from './fail.png';
import green from './green.png';
import lightside from './lightside.png';
import npc from './npc.png';
import pc from './pc.png';
import purple from './purple.png';
import red from './red.png';
import repeat from './repeat.png';
import success from './success.png';
import threat from './threat.png';
import triumph from './triumph.png';
import upgrade from './upgrade.png';
import white from './white.png';
import x from './x.png';
import yellow from './yellow.png';
import empty from './empty.png';

export const ADVANTAGE = advantage;
export const BLACK = black;
export const BLUE = blue;
export const DARKSIDE = darkside;
export const DESPAIR = despair;
export const DOWNGRADE = downgrade;
export const FAIL = fail;
export const GREEN = green;
export const LIGHTSIDE = lightside;
export const NPC = npc;
export const PC = pc;
export const PURPLE = purple;
export const RED = red;
export const REPEAT = repeat;
export const SUCCESS = success;
export const THREAT = threat;
export const TRIUMPH = triumph;
export const UPGRADE = upgrade;
export const WHITE = white;
export const X = x;
export const YELLOW = yellow;
export const EMPTY = empty;