export const CREATE_NEW_CHARACTER = "CREATE_NEW_CHARACTER";
export const ADD_SKILL = "ADD_SKILL";
export const DELETE_SKILL = "DELETE_SKILL";
export const ADD_CHARACTERISTIC = "ADD_CHARACTERISTIC";
export const DELETE_CHARACTERISTIC = "DELETE_CHARACTERISTIC";
export const ADD_MESSAGE = "ADD_MESSAGE";